name: Build Master

on:
  push:
    branches: [ master ]

jobs:
  test:
    name: Run Unit Tests
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v1
      - name: Setup JDK
        uses: actions/setup-java@v1
        with:
          java-version: 1.8
      - name: Run Tests
        run: bash ./gradlew test --stacktrace  
  aab:
    name: Generate AAB
    needs: test
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v1
      - name: Setup JDK
        uses: actions/setup-java@v1
        with:
          java-version: 1.8
      - name: Build AAB
        run: bash ./gradlew bundle assemble --stacktrace
      - name: Upload AAB
        uses: actions/upload-artifact@v1
        with:
          name: aab
          path: app/build/outputs/bundle/
  upload:
    name: Upload AAB
    needs: aab
    runs-on: ubuntu-latest
    steps:
      - name: Download AAB from build
        uses: actions/download-artifact@v1
        with:
          name: aab
      - name: Rename files
        run: |
          mv aab/debug/app-debug.aab aab/debug/app-debug-${{ github.run_number }}.aab
          mv aab/release/app-release.aab aab/release/app-release-${{ github.run_number }}.aab
      - name: Create Release
        id: create_release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }} 
        with:
          tag_name: r${{ github.run_number }}
          release_name: r${{ github.run_number }}
      - name: Upload Release AAB
        id: upload_release_asset
        uses: actions/upload-release-asset@v1.0.1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ steps.create_release.outputs.upload_url }}
          asset_path: aab/
          asset_content_type: application/zip
          
